import { useEffect, useMemo, useState } from 'react';
import { Alert, Share, Switch, View } from 'react-native';
import { Text } from '../components/Typography';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Bell, Bug, Database, FolderCog, Tags, UserCog, UsersRound } from 'lucide-react-native';
import { API_URL, api, errorMessage } from '../api';
import { Button, Card, Field, Screen, StateView, Title } from '../components/ui';
import { loadImportInbox, loadQueue } from '../storage';
import { useAuth } from '../state/AuthContext';
import { usePreferences } from '../state/PreferencesContext';
import { useAppTheme } from '../theme';

const ref = (value: any) => String(value?._id || value || '');
const colorsList = ['#2563EB', '#7C3AED', '#059669', '#DC2626', '#D97706', '#0891B2'];

export function HouseholdScreen({ navigation }: any) {
  const { colors } = useAppTheme(); const { user, households, activeHouseholdId, selectHousehold, refreshHouseholds } = useAuth(); const [inviteToken, setInviteToken] = useState('');
  async function acceptInvite() { try { const joined = (await api.acceptHouseholdInvite(inviteToken.trim())).data; await refreshHouseholds(); await selectHousehold(joined.householdId); setInviteToken(''); Alert.alert('Household joined', `You now share ${joined.householdName || 'this household'} data.`); } catch (cause) { Alert.alert('Could not accept invitation', errorMessage(cause)); } }
  return <Screen><Title subtitle="Shared financial workspace, collaborators, taxonomy, and defaults.">Household & configuration</Title>
    <Card><Text style={{ color: colors.text, fontWeight: '900' }}>Active household</Text>{households.map((entry) => <Button key={entry.householdId} label={`${entry.householdId === activeHouseholdId ? '✓ ' : ''}${entry.householdName} · ${entry.role}`} variant={entry.householdId === activeHouseholdId ? 'primary' : 'secondary'} align="left" onPress={() => selectHousehold(entry.householdId)} />)}<Field label="Invitation token" value={inviteToken} onChangeText={setInviteToken} autoCapitalize="none" /><Button label="Accept household invitation" disabled={!inviteToken.trim()} onPress={acceptInvite} /></Card>{[
    ['Members', 'Create, edit, archive, and review member summaries.', 'Members', UsersRound],
    ['Categories', 'Manage categories, subcategories, and quick-entry favorites.', 'Categories', Tags],
    ['Collaborators', user?.isDemo ? 'Unavailable for demo data.' : 'Invite family members and manage access.', 'Users', UserCog],
    ['Preferences & diagnostics', 'Regional defaults, notifications, cache, and environment.', 'Preferences', FolderCog],
  ].map(([title, subtitle, screen, Icon]: any) => <Card key={screen}><View style={{ flexDirection: 'row', gap: 12 }}><Icon color={colors.primary} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: '900' }}>{title}</Text><Text style={{ color: colors.textMuted }}>{subtitle}</Text></View></View><Button label={`Open ${String(title).toLowerCase()}`} variant="secondary" disabled={screen === 'Users' && !!user?.isDemo} onPress={() => navigation.navigate(screen)} /></Card>)}</Screen>;
}

export function MembersScreen({ navigation }: any) {
  const { colors } = useAppTheme(); const [rows, setRows] = useState<any[]>([]); const [home, setHome] = useState<any>(null);
  async function load() { try { const now = new Date(); const [members, snapshot] = await Promise.all([api.members(), api.home(now.getMonth() + 1, now.getFullYear())]); setRows(members.data); setHome(snapshot.data); } catch (cause) { Alert.alert('Could not load members', errorMessage(cause)); } }
  useEffect(() => { load(); }, []);
  return <Screen><Title subtitle="Archiving preserves transaction references.">Household members</Title><Button label="Add member" onPress={() => navigation.navigate('MemberForm')} />{rows.map((item) => <Card key={item._id}><View style={{ flexDirection: 'row', gap: 12 }}><View style={{ width: 42, height: 42, borderRadius: 15, backgroundColor: item.color, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#fff', fontWeight: '900' }}>{item.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: '900' }}>{item.name}</Text><Text style={{ color: colors.textMuted }}>{item.role}</Text></View></View><Text style={{ color: colors.textMuted }}>Monthly household totals: income {home?.summary?.totalIncome ?? '—'} · expense {home?.summary?.netExpense ?? '—'}. Select this member on Home for member-only totals.</Text><Button label="Edit member" variant="secondary" onPress={() => navigation.navigate('MemberForm', { item })} /></Card>)}</Screen>;
}

export function MemberFormScreen({ navigation, route }: any) {
  const item = route.params?.item; const prefs = usePreferences(); const [form, setForm] = useState({ name: item?.name || '', role: item?.role || 'other', color: item?.color || colorsList[0] });
  async function save() { try { item ? await api.updateMember(item._id, form) : await api.createMember(form); navigation.goBack(); } catch (cause) { Alert.alert('Could not save member', errorMessage(cause)); } }
  return <Screen><Title>{item ? 'Edit member' : 'Add member'}</Title><Field label="Name" value={form.name} onChangeText={(name) => setForm({ ...form, name })} /><Card><Text>Role</Text>{['self', 'husband', 'other'].map((role) => <Button key={role} label={role} variant={form.role === role ? 'primary' : 'secondary'} onPress={() => setForm({ ...form, role })} />)}</Card><Card><Text>Color</Text>{colorsList.map((color) => <Button key={color} label={color} variant={form.color === color ? 'primary' : 'secondary'} onPress={() => setForm({ ...form, color })} />)}</Card><Button label="Save member" onPress={save} />{item && <Button label={prefs.homeMemberId === item._id ? 'Default member ✓' : 'Use as default member'} variant="secondary" onPress={() => prefs.updatePreferences({ homeMemberId: item._id })} />}{item && <Button label="Archive member" variant="danger" onPress={() => Alert.alert('Archive member?', 'Dhanam will reject this if referenced records cannot safely retain the member.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { try { await api.archiveMember(item._id); navigation.goBack(); } catch (cause) { Alert.alert('Cannot archive member', errorMessage(cause)); } } }])} />}</Screen>;
}

export function CategoriesScreen({ navigation }: any) {
  const { colors } = useAppTheme(); const [rows, setRows] = useState<any[]>([]);
  async function load() { try { setRows((await api.categories()).data); } catch (cause) { Alert.alert('Could not load categories', errorMessage(cause)); } }
  useEffect(() => { load(); }, []);
  return <Screen><Title subtitle="Bulk merging and taxonomy cleanup remain web-first.">Categories & subcategories</Title><Button label="Add category" onPress={() => navigation.navigate('CategoryForm')} />{rows.map((item) => <Card key={item._id}><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ width: 12, height: 12, borderRadius: 6, marginTop: 5, backgroundColor: item.color || colors.primary }} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: '900' }}>{item.name}</Text><Text style={{ color: colors.textMuted }}>{item.description || 'No description'}</Text></View></View><Button label="Edit category" variant="secondary" onPress={() => navigation.navigate('CategoryForm', { item })} /><Button label="Manage subcategories" variant="secondary" onPress={() => navigation.navigate('Subcategories', { category: item })} /></Card>)}</Screen>;
}

export function CategoryFormScreen({ navigation, route }: any) {
  const item = route.params?.item; const [form, setForm] = useState({ name: item?.name || '', description: item?.description || '', color: item?.color || colorsList[0] });
  async function save() { try { item ? await api.updateCategory(item._id, form) : await api.createCategory(form); navigation.goBack(); } catch (cause) { Alert.alert('Could not save category', errorMessage(cause)); } }
  return <Screen><Title>{item ? 'Edit category' : 'Add category'}</Title><Field label="Name" value={form.name} onChangeText={(name) => setForm({ ...form, name })} /><Field label="Description" value={form.description} onChangeText={(description) => setForm({ ...form, description })} /><Card><Text>Color</Text>{colorsList.map((color) => <Button key={color} label={color} variant={form.color === color ? 'primary' : 'secondary'} onPress={() => setForm({ ...form, color })} />)}</Card><Button label="Save category" onPress={save} />{item && <Button label="Archive category" variant="danger" onPress={() => Alert.alert('Archive category?', 'Existing transactions may prevent destructive removal.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { try { await api.archiveCategory(item._id); navigation.goBack(); } catch (cause) { Alert.alert('Cannot archive category', errorMessage(cause)); } } }])} />}</Screen>;
}

export function SubcategoriesScreen({ route }: any) {
  const { colors } = useAppTheme(); const category = route.params.category; const [rows, setRows] = useState<any[]>([]); const [name, setName] = useState(''); const [editingId, setEditingId] = useState(''); const [editingName, setEditingName] = useState('');
  async function load() { try { setRows((await api.subcategories(category._id)).data); } catch (cause) { Alert.alert('Could not load subcategories', errorMessage(cause)); } }
  useEffect(() => { load(); }, []);
  async function add() { if (!name.trim()) return; try { await api.createSubcategory(category._id, { name }); setName(''); load(); } catch (cause) { Alert.alert('Could not add subcategory', errorMessage(cause)); } }
  async function rename(id: string) { if (!editingName.trim()) return; try { await api.updateSubcategory(id, { name: editingName.trim() }); setEditingId(''); setEditingName(''); load(); } catch (cause) { Alert.alert('Could not rename subcategory', errorMessage(cause)); } }
  return <Screen><Title subtitle={category.name}>Subcategories</Title><Field label="New subcategory" value={name} onChangeText={setName} /><Button label="Add subcategory" onPress={add} />{rows.map((item) => <Card key={item._id}>{editingId === item._id ? <><Field label="Subcategory name" value={editingName} onChangeText={setEditingName} autoFocus /><Button label="Save name" onPress={() => rename(item._id)} /><Button label="Cancel" variant="secondary" onPress={() => setEditingId('')} /></> : <><Text style={{ color: colors.text, fontWeight: '900' }}>{item.name}</Text><Button label="Rename" variant="secondary" onPress={() => { setEditingId(item._id); setEditingName(item.name); }} /></>}<Button label="Archive" variant="danger" onPress={() => Alert.alert('Archive subcategory?', undefined, [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { try { await api.archiveSubcategory(item._id); load(); } catch (cause) { Alert.alert('Cannot archive', errorMessage(cause)); } } }])} /></Card>)}</Screen>;
}

export function UsersScreen({ navigation }: any) {
  const { colors } = useAppTheme(); const { user, activeHouseholdId } = useAuth(); const [rows, setRows] = useState<any[]>([]);
  async function load() { if (!user?.isDemo && activeHouseholdId) try { setRows((await api.householdMembers(activeHouseholdId)).data); } catch (cause) { Alert.alert('Could not load collaborators', errorMessage(cause)); } }
  async function update(item: any, data: Record<string, unknown>) { try { await api.updateHouseholdMember(activeHouseholdId, item.id, data); await load(); } catch (cause) { Alert.alert('Could not update access', errorMessage(cause)); } }
  async function transfer(item: any) { try { await api.transferHouseholdOwnership(activeHouseholdId, item.id); await load(); } catch (cause) { Alert.alert('Could not transfer ownership', errorMessage(cause)); } }
  useEffect(() => { load(); }, [activeHouseholdId]);
  if (user?.isDemo) return <Screen><StateView kind="empty" title="Unavailable in demo mode" message="User administration is hidden for shared sample data." /></Screen>;
  const self = rows.find((item) => String(item.userId) === user?._id); const canManage = self?.role === 'owner' || self?.role === 'admin';
  return <Screen><Title subtitle="Each person signs in separately but contributes to the same household data.">Collaborators</Title>{canManage && <Button label="Invite collaborator" onPress={() => navigation.navigate('UserForm')} />}{rows.map((item) => <Card key={item.id}><Text style={{ color: colors.text, fontWeight: '900' }}>{item.email}{String(item.userId) === user?._id ? ' · You' : ''}</Text><Text style={{ color: colors.textMuted }}>{item.role} · {item.status}</Text>{self?.role === 'owner' && item.role !== 'owner' && item.status === 'active' && <><Button label={item.role === 'admin' ? 'Change to contributor' : 'Promote to admin'} variant="secondary" onPress={() => update(item, { role: item.role === 'admin' ? 'contributor' : 'admin' })} /><Button label="Transfer ownership" variant="secondary" onPress={() => Alert.alert('Transfer ownership?', `${item.email} will become the owner and you will become an admin.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Transfer', onPress: () => transfer(item) }])} /></>}{canManage && item.role !== 'owner' && <Button label="Remove access" variant="danger" onPress={() => Alert.alert('Remove collaborator?', 'They will immediately lose access to this household. Shared records will remain.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => update(item, { status: 'removed' }) }])} />}</Card>)}</Screen>;
}

export function UserFormScreen({ navigation, route }: any) {
  const { activeHouseholdId } = useAuth(); const [email, setEmail] = useState(''); const [role, setRole] = useState<'admin' | 'contributor'>('contributor');
  async function save() { try { const result: any = (await api.inviteHouseholdMember(activeHouseholdId, email.trim().toLowerCase(), role)).data; Alert.alert('Invitation created', result.inviteToken ? `Development invitation token:\n${result.inviteToken}` : 'An invitation email has been sent.'); navigation.goBack(); } catch (cause) { Alert.alert('Could not invite collaborator', errorMessage(cause)); } }
  return <Screen><Title subtitle="They must sign in using this exact email address.">Invite collaborator</Title><Field label="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" /><Card><Text>Access level</Text><Button label="Contributor · manage financial records" variant={role === 'contributor' ? 'primary' : 'secondary'} onPress={() => setRole('contributor')} /><Button label="Admin · records and invitations" variant={role === 'admin' ? 'primary' : 'secondary'} onPress={() => setRole('admin')} /></Card><Button label="Send invitation" disabled={!email.trim()} onPress={save} /></Screen>;
}

export function NotificationsScreen({ route, navigation }: any) {
  const { colors } = useAppTheme(); const [items, setItems] = useState<any[]>(route.params?.items || []); const [imports, setImports] = useState<any[]>([]); const [queue, setQueue] = useState<any[]>([]);
  useEffect(() => { Promise.all([loadImportInbox(), loadQueue()]).then(([inbox, sync]) => { setImports(inbox.filter((item) => ['needs_review', 'duplicate_suspected', 'failed'].includes(item.status))); setQueue(sync); }); }, []);
  return <Screen><Title subtitle="Actionable alerts from finance rules and this device.">Notification inbox</Title>{!items.length && !imports.length && !queue.length && <StateView kind="empty" message="You’re all caught up." />}{items.map((item) => <Card key={item.id}><Text style={{ color: colors.text, fontWeight: '900' }}>{item.title}</Text><Text style={{ color: colors.textMuted }}>{item.message}</Text></Card>)}{imports.map((item) => <Card key={item.id}><Text style={{ color: colors.warning, fontWeight: '900' }}>Import {item.status.replace('_', ' ')}</Text><Text style={{ color: colors.textMuted }}>{item.draft?.description || item.error}</Text><Button label="Review imports" variant="secondary" onPress={() => navigation.navigate('ImportInbox')} /></Card>)}{queue.map((item) => <Card key={item.id}><Text style={{ color: colors.danger, fontWeight: '900' }}>Sync {item.status}</Text><Text style={{ color: colors.textMuted }}>{item.operation} · {item.error || 'Waiting for connection'}</Text></Card>)}<Button label="Notification controls" variant="secondary" onPress={() => navigation.navigate('NotificationSettings')} /></Screen>;
}

export function NotificationSettingsScreen() {
  const { colors } = useAppTheme(); const { user, updateUser } = useAuth(); const current = user?.notificationPreferences || { enabled: false, recurring: true, cardDue: true, budgets: true }; const [prefs, setPrefs] = useState<any>({ ...current, quietStart: '22:00', quietEnd: '07:00', recurringAdvanceDays: '2', cardAdvanceDays: '5', showAmounts: false });
  async function save() { try { await updateUser({ notificationPreferences: prefs }); Alert.alert('Notification preferences saved', 'Push delivery still requires a configured device-token service. In-app alerts are active now.'); } catch (cause) { Alert.alert('Could not save preferences', errorMessage(cause)); } }
  const toggle = (key: string, label: string) => <View style={{ flexDirection: 'row', alignItems: 'center' }}><Text style={{ color: colors.text, flex: 1 }}>{label}</Text><Switch value={!!prefs[key]} onValueChange={(value) => setPrefs({ ...prefs, [key]: value })} /></View>;
  return <Screen><Title subtitle="Sensitive amounts remain hidden from lock-screen text by default.">Notification controls</Title><Card>{toggle('enabled', 'Enable notifications')}{toggle('recurring', 'Recurring due reminders')}{toggle('cardDue', 'Card due reminders')}{toggle('budgets', 'Budget and goal warnings')}{toggle('showAmounts', 'Show amounts on lock screen')}</Card><Field label="Quiet hours start" value={prefs.quietStart} onChangeText={(quietStart) => setPrefs({ ...prefs, quietStart })} /><Field label="Quiet hours end" value={prefs.quietEnd} onChangeText={(quietEnd) => setPrefs({ ...prefs, quietEnd })} /><Field label="Recurring reminder days ahead" value={prefs.recurringAdvanceDays} onChangeText={(recurringAdvanceDays) => setPrefs({ ...prefs, recurringAdvanceDays })} keyboardType="number-pad" /><Field label="Card reminder days ahead" value={prefs.cardAdvanceDays} onChangeText={(cardAdvanceDays) => setPrefs({ ...prefs, cardAdvanceDays })} keyboardType="number-pad" /><Button label="Save notification settings" onPress={save} /><Card><Text style={{ color: colors.text, fontWeight: '900' }}>Native surfaces</Text><Text style={{ color: colors.textMuted }}>App-icon shortcuts are active. Widgets, push delivery, quick-settings controls, receipt camera, and OCR remain gated on their native services and storage design.</Text></Card></Screen>;
}

export function PreferencesScreen({ navigation }: any) {
  const { colors } = useAppTheme(); const { user, updateUser } = useAuth(); const prefs = usePreferences(); const [locale, setLocale] = useState(user?.locale || 'en-AE'); const [currency, setCurrency] = useState<'AED' | 'INR'>(user?.currency || 'AED');
  async function save() { try { await updateUser({ locale, currency }); Alert.alert('Regional preferences saved'); } catch (cause) { Alert.alert('Could not save preferences', errorMessage(cause)); } }
  return <Screen><Title subtitle="Regional formatting, privacy, notifications, cache, and environment.">Preferences</Title><Card><Text style={{ color: colors.text, fontWeight: '900' }}>Region</Text><Field label="Locale" value={locale} onChangeText={setLocale} /><View style={{ flexDirection: 'row', gap: 8 }}>{(['AED', 'INR'] as const).map((value) => <Button key={value} label={value} variant={currency === value ? 'primary' : 'secondary'} onPress={() => setCurrency(value)} />)}</View><Button label="Save region" onPress={save} /></Card><Card><Text style={{ color: colors.text, fontWeight: '900' }}>Appearance and privacy</Text>{(['light', 'dark', 'system'] as const).map((mode) => <Button key={mode} label={mode} variant={prefs.themeMode === mode ? 'primary' : 'secondary'} onPress={() => prefs.updatePreferences({ themeMode: mode })} />)}<Button label={`Privacy mode ${prefs.privacyMode ? 'on' : 'off'}`} variant="secondary" onPress={() => prefs.updatePreferences({ privacyMode: !prefs.privacyMode })} /><Button label="Security and app lock" variant="secondary" onPress={() => navigation.navigate('Security')} /></Card><Card><Text style={{ color: colors.text, fontWeight: '900' }}>About Dhanam Tracker</Text><Text style={{ color: colors.textMuted }}>• Personal expense and budget tracker</Text><Text style={{ color: colors.textMuted }}>• User-entered records only</Text><Text style={{ color: colors.textMuted }}>• No banking integration</Text><Text style={{ color: colors.textMuted }}>• No financial transactions</Text><Text style={{ color: colors.textMuted }}>• No payment processing</Text></Card><Button label="Notification controls" variant="secondary" onPress={() => navigation.navigate('NotificationSettings')} icon={<Bell size={17} color={colors.text} />} /><Button label="Diagnostics" variant="secondary" onPress={() => navigation.navigate('Diagnostics')} icon={<Bug size={17} color={colors.text} />} /><Button label="Clear learned message mappings" variant="danger" onPress={() => Alert.alert('Clear learned mappings?', undefined, [{ text: 'Cancel', style: 'cancel' }, { text: 'Clear', style: 'destructive', onPress: async () => { await api.clearMessageLearnings(); } }])} /></Screen>;
}

export function DiagnosticsScreen() {
  const { colors } = useAppTheme(); const [data, setData] = useState<any>(null);
  useEffect(() => { Promise.all([AsyncStorage.getAllKeys(), loadQueue(), loadImportInbox()]).then(async ([keys, queue, inbox]) => { const entries = await AsyncStorage.multiGet(keys); const bytes = entries.reduce((sum, [, value]) => sum + (value?.length || 0), 0); setData({ apiUrl: API_URL, appVersion: '2.0.0', cachedKeys: keys.length, approximateCacheBytes: bytes, queue: queue.map(({ operation, status, error }) => ({ operation, status, error })), importStatuses: inbox.reduce((map: any, item) => ({ ...map, [item.status]: (map[item.status] || 0) + 1 }), {}) }); }); }, []);
  async function share() { if (!data) return; await Share.share({ message: `Dhanam diagnostics\nVersion: ${data.appVersion}\nAPI: ${data.apiUrl}\nCache keys: ${data.cachedKeys}\nApprox bytes: ${data.approximateCacheBytes}\nSync: ${JSON.stringify(data.queue)}\nImports: ${JSON.stringify(data.importStatuses)}` }); }
  return <Screen><Title subtitle="Contains environment and sync status only—never amounts or descriptions.">Diagnostics</Title>{!data ? <StateView kind="loading" /> : <Card><Text style={{ color: colors.text }}>App version: {data.appVersion}</Text><Text style={{ color: colors.text }}>API environment: {data.apiUrl}</Text><Text style={{ color: colors.text }}>Local keys: {data.cachedKeys}</Text><Text style={{ color: colors.text }}>Approximate local data: {data.approximateCacheBytes} bytes</Text><Text style={{ color: colors.text }}>Queued mutations: {data.queue.length}</Text><Text style={{ color: colors.text }}>Import statuses: {JSON.stringify(data.importStatuses)}</Text></Card>}<Button label="Share scrubbed diagnostics" variant="secondary" onPress={share} /><Button label="Clear non-secure local cache" variant="danger" onPress={() => Alert.alert('Clear local cache?', 'Secure login and app-lock credentials are not affected.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Clear', style: 'destructive', onPress: async () => { const keys = await AsyncStorage.getAllKeys(); const safe = keys.filter((key) => key.startsWith('dhanam.cache.') || key.includes('assistant.history')); if (safe.length) await AsyncStorage.multiRemove(safe); Alert.alert('Cache cleared'); } }])} /></Screen>;
}
